-- MySQL数据库表结构创建脚本

-- 0. sys_config表 (系统配置表)
DROP TABLE IF EXISTS sys_config;
CREATE TABLE sys_config (
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  key_name VARCHAR(100) NOT NULL COMMENT '键名',
  key_value VARCHAR(500) DEFAULT NULL COMMENT '键值',
  description VARCHAR(500) DEFAULT NULL COMMENT '描述',
  create_by VARCHAR(50) DEFAULT NULL COMMENT '创建人',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by VARCHAR(50) DEFAULT NULL COMMENT '更新人',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  del_flag TINYINT(1) DEFAULT 0 COMMENT '删除标志(0:未删除 1:已删除)',
  PRIMARY KEY (id),
  UNIQUE KEY uk_key_name (key_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统配置表';

-- 1. demo表 (测试表)
DROP TABLE IF EXISTS demo;
CREATE TABLE demo (
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  name VARCHAR(30) DEFAULT NULL COMMENT '姓名',
  sex VARCHAR(2) DEFAULT NULL COMMENT '性别',
  age INT(11) DEFAULT NULL COMMENT '年龄',
  birthday DATE DEFAULT NULL COMMENT '生日',
  email VARCHAR(50) DEFAULT NULL COMMENT '邮箱',
  content VARCHAR(1000) DEFAULT NULL COMMENT '个人简介',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='测试表';

-- 2. app_user表 (用户表)
DROP TABLE IF EXISTS app_user;
CREATE TABLE app_user (
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  username VARCHAR(50) DEFAULT NULL COMMENT '用户名',
  nick_name VARCHAR(50) DEFAULT NULL COMMENT '昵称',
  avatar_url VARCHAR(255) DEFAULT NULL COMMENT '头像URL',
  gender VARCHAR(2) DEFAULT NULL COMMENT '性别(1:男 2:女)',
  phone VARCHAR(20) DEFAULT NULL COMMENT '手机号',
  birthday DATETIME DEFAULT NULL COMMENT '出生日期',
  country VARCHAR(50) DEFAULT NULL COMMENT '国家',
  province VARCHAR(50) DEFAULT NULL COMMENT '省份',
  city VARCHAR(50) DEFAULT NULL COMMENT '城市',
  openid VARCHAR(50) DEFAULT NULL COMMENT '微信openid',
  unionid VARCHAR(50) DEFAULT NULL COMMENT '微信unionid',
  status VARCHAR(10) DEFAULT NULL COMMENT '状态',
  gestational_week INT DEFAULT NULL COMMENT '当前孕周',
  gestational_time DATETIME DEFAULT NULL COMMENT '填写时间',
  start_time DATETIME DEFAULT NULL COMMENT '开始时间',
  end_time DATETIME DEFAULT NULL COMMENT '离馆时间',
  mom_birthday DATE DEFAULT NULL COMMENT '妈妈生日',
  baby_birthday DATE DEFAULT NULL COMMENT '宝宝生日',
  home_address VARCHAR(255) DEFAULT NULL COMMENT '家庭住址',
  occupancy_type VARCHAR(50) DEFAULT NULL COMMENT '入住房型',
  room_num VARCHAR(20) DEFAULT NULL COMMENT '房号',
  wedding_anniversary DATETIME DEFAULT NULL COMMENT '结婚纪念日',
  parity BIGINT DEFAULT NULL COMMENT '胎次',
  allergen VARCHAR(255) DEFAULT NULL COMMENT '致敏源',
  special_medical_history VARCHAR(255) DEFAULT NULL COMMENT '特殊病史',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  create_by VARCHAR(50) DEFAULT NULL COMMENT '创建人',
  update_by VARCHAR(50) DEFAULT NULL COMMENT '更新人',
  del_flag TINYINT(1) DEFAULT 0 COMMENT '删除标志(0:未删除 1:已删除)',
  PRIMARY KEY (id),
  INDEX idx_openid (openid),
  INDEX idx_phone (phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

-- 3. mmcc_activity表 (活动主表)
DROP TABLE IF EXISTS mmcc_activity;
CREATE TABLE mmcc_activity (
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  name VARCHAR(100) NOT NULL COMMENT '活动名称',
  activity_user_name VARCHAR(50) DEFAULT NULL COMMENT '活动联系人姓名',
  activity_user_phone VARCHAR(20) DEFAULT NULL COMMENT '联系人手机号',
  start_time DATETIME DEFAULT NULL COMMENT '报名开始时间',
  end_time DATETIME DEFAULT NULL COMMENT '报名截止时间',
  introduce TEXT DEFAULT NULL COMMENT '活动介绍',
  end_state VARCHAR(2) DEFAULT '0' COMMENT '结束状态(0:未结束 1:已结束)',
  file_url VARCHAR(255) DEFAULT NULL COMMENT '图片地址',
  achieve VARCHAR(255) DEFAULT NULL COMMENT '活动成就',
  sort BIGINT DEFAULT 0 COMMENT '排序',
  status VARCHAR(10) DEFAULT '0' COMMENT '状态(0:草稿 10:发布 20:截止)',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  create_by VARCHAR(50) DEFAULT NULL COMMENT '创建人',
  update_by VARCHAR(50) DEFAULT NULL COMMENT '更新人',
  del_flag TINYINT(1) DEFAULT 0 COMMENT '删除标志(0:未删除 1:已删除)',
  PRIMARY KEY (id),
  INDEX idx_status (status),
  INDEX idx_end_state (end_state)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='孕期圈活动表';

-- 4. mmcc_activity_file表 (活动图片表)
DROP TABLE IF EXISTS mmcc_activity_file;
CREATE TABLE mmcc_activity_file (
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  activity_id BIGINT(20) NOT NULL COMMENT '活动ID',
  file_url VARCHAR(255) NOT NULL COMMENT '图片地址',
  status VARCHAR(10) DEFAULT NULL COMMENT '状态',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  create_by VARCHAR(50) DEFAULT NULL COMMENT '创建人',
  update_by VARCHAR(50) DEFAULT NULL COMMENT '更新人',
  del_flag TINYINT(1) DEFAULT 0 COMMENT '删除标志(0:未删除 1:已删除)',
  PRIMARY KEY (id),
  INDEX idx_activity_id (activity_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='活动图片表';

-- 5. mmcc_activity_user表 (用户活动关联表)
DROP TABLE IF EXISTS mmcc_activity_user;
CREATE TABLE mmcc_activity_user (
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  activity_id BIGINT(20) NOT NULL COMMENT '活动ID',
  user_id BIGINT(20) NOT NULL COMMENT '用户ID',
  status VARCHAR(10) DEFAULT NULL COMMENT '状态',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  create_by VARCHAR(50) DEFAULT NULL COMMENT '创建人',
  update_by VARCHAR(50) DEFAULT NULL COMMENT '更新人',
  del_flag TINYINT(1) DEFAULT 0 COMMENT '删除标志(0:未删除 1:已删除)',
  PRIMARY KEY (id),
  UNIQUE KEY uk_activity_user (activity_id, user_id),
  INDEX idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户活动关联表';
