-- 展示用户预定表
CREATE TABLE `mmcc_service_user` (
  `id` varchar(32) NOT NULL COMMENT '主键ID',
  `display_id` varchar(32) DEFAULT NULL COMMENT '服务展示id',
  `user_name` varchar(50) DEFAULT NULL COMMENT '用户姓名',
  `user_phone` varchar(20) DEFAULT NULL COMMENT '用户手机号',
  `visiting_time` datetime DEFAULT NULL COMMENT '参观时间',
  `user_id` varchar(32) DEFAULT NULL COMMENT '用户id',
  `gestational_week` varchar(10) DEFAULT NULL COMMENT '孕周',
  `residence` varchar(100) DEFAULT NULL COMMENT '住宅',
  `inspect_hospital` varchar(100) DEFAULT NULL COMMENT '产检医院',
  `visitors_num` varchar(10) DEFAULT NULL COMMENT '参观人数',
  `accompanying_relationship` varchar(50) DEFAULT NULL COMMENT '陪同人员关系',
  `with_children` varchar(2) DEFAULT NULL COMMENT '是否带孩子（0：是 1：否）',
  `age_group` varchar(10) DEFAULT NULL COMMENT '年龄段',
  `parity` bigint(20) DEFAULT NULL COMMENT '胎次',
  `crib` varchar(2) DEFAULT NULL COMMENT '是否需要婴儿床（0：是 1：否）',
  `snack` varchar(2) DEFAULT NULL COMMENT '点心饮品',
  `beverage_type` varchar(10) DEFAULT NULL COMMENT '饮品选择',
  `food_tasting` varchar(100) DEFAULT NULL COMMENT '月子餐品鉴',
  `meal_menu` varchar(255) DEFAULT NULL COMMENT '月子餐菜单',
  `servings_num` varchar(10) DEFAULT NULL COMMENT '陪护餐份数',
  `umbrella` varchar(2) DEFAULT NULL COMMENT '是否需要带雨伞（0：是1：否）',
  `parking` varchar(2) DEFAULT NULL COMMENT '保安泊车（0：是 1：否）',
  `pickup` varchar(2) DEFAULT NULL COMMENT '是否需要接送（0：是 1：否）',
  `safety_seat` varchar(2) DEFAULT NULL COMMENT '儿童安全椅（0：是 1否）',
  `other_requirements` text DEFAULT NULL COMMENT '其他要求',
  `scheduled_time` datetime DEFAULT NULL COMMENT '预定时间',
  `evaluate_time` datetime DEFAULT NULL COMMENT '评价时间',
  `evaluate_content` text DEFAULT NULL COMMENT '评价内容',
  `status` varchar(10) DEFAULT NULL COMMENT '状态（-1：未到店 0：未评价 1已评价）',
  `send_message` varchar(10) DEFAULT NULL COMMENT '消息发送状态',
  `service_person_id` varchar(32) DEFAULT NULL COMMENT '接待人员id',
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint(1) DEFAULT '0' COMMENT '删除标志',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='展示用户预定表';
